#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 10

for (( i=1; i<= 100; i++))
do
	if (( i%15==0))
	then
		echo 'FizzBuzzz'
	elif (( i%3==0))
	then
		echo 'Fizz'
	elif ((i%5==0))
	then
		echo 'Buzz'
	else
		echo "$i"
	fi
done
