#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
hrs=0
mins=1
while [ $hrs -le 12 ]
do
	echo "Hours: $hrs"
	while [ $mins -le 59 ]
	do
		echo "Minutes: $mins"
		((mins++))
	done
	mins=1
	((hrs++))
done
